export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'

export const GET_MONGOPROJECTS_SUCCESS = 'GET_MONGOPROJECTS_SUCCESS'
export const GET_MONGOPROJECTS_REQUEST = 'GET_MONGOPROJECTS_REQUEST'
export const ADD_MONGOPROJECT_SUCCESS = 'ADD_MONGOPROJECT_SUCCESS'
export const ADD_MONGOPROJECT_REQUEST = 'ADD_MONGOPROJECT_REQUEST'