FROM esquire/esquire-build AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY package.json ./
RUN dotnet restore
RUN npm install

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM esquire/esquire-runtime
ENV ASPNETCORE_ENVIRONMENT=Production
ENV NODE_ENV=production
ENV ASPNETCORE_URLS http://*:5000

# MongoDB Ports
EXPOSE 27017
EXPOSE 28017

# SQL Server port
EXPOSE 1433

WORKDIR /app

# App port
EXPOSE 5000

COPY --from=build-env /app/out .
COPY ./dockerfiles/run_prod.sh .

ENTRYPOINT ["/bin/bash", "/app/run_prod.sh"]
